/*
 * generated by Xtext 2.20.0
 */
package de.systemticks.c4.ide

import com.google.inject.Guice
import de.systemticks.c4.C4DslRuntimeModule
import de.systemticks.c4.C4DslStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class C4DslIdeSetup extends C4DslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new C4DslRuntimeModule, new C4DslIdeModule))
	}
	
}
