image:
  file: .gitpod.Dockerfile

tasks:
  - init: cd extension && yarn install && yarn build-all
    command: yarn

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test