image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      sdk default java 11.0.16.fx-zulu 
      cd extension
      yarn install
      yarn build-all
    command: yarn

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - tenninebt.vscode-koverage