variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - server
  - client
  - deploy

c4-language-server:
  image: gradle:jdk11
  stage: server

  script:
    - cd server/c4-dsl-language-server
    - ./gradlew check
    - ./gradlew deploy

  artifacts:
    when: always
    reports:
      junit: language-server/build/test-results/test/**/TEST-*.xml
    paths: 
      - extension/server/c4-language-server
      - language-server/build/reports/jacoco/test/html
    expire_in: 60 min

c4-language-client:
  image: node:14
  stage: client

  variables:
    NODE_ENV: "development"

  script:
    - cd extension
    - yarn install 
    - yarn build
    - yarn global add vsce
    - vsce package
    - cat ../language-server/build/reports/jacoco/test/html/index.html | grep -o 'Total[^%]*%'

  dependencies:
    - c4-language-server

  artifacts:
    paths:
      - extension/*.vsix
    expire_in: 1 day

pages:
  stage: deploy
  dependencies:
    -  c4-language-server
  script:
    - mv language-server/build/reports/jacoco/test/html/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master