variables:
  GIT_SUBMODULE_STRATEGY: recursive
  LANGUAGE_SERVER_DIR: server/c4-dsl-language-server

stages:
  - test
  - server
  - client
  - deploy

c4-server-test:
  image: gradle:jdk17
  stage: test
  script:
    - cd $LANGUAGE_SERVER_DIR
    - ./gradlew test
    - cat ./build/reports/jacoco/test/html/index.html | grep -o 'Total[^%]*%'
  coverage: "/Total.*?([0-9]{1,3})%/"
  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/$LANGUAGE_SERVER_DIR/build/reports/jacoco/test/html

c4-client-test:
  image: node:16
  stage: test
  script:
    - cd extension
    - yarn install
    - yarn build
    - apt update
    - apt install -y libasound2 libgbm1 libgtk-3-0 libnss3 xvfb
    - xvfb-run -a yarn test

c4-language-server:
  image: gradle:jdk17
  stage: server

  script:
    - cd $LANGUAGE_SERVER_DIR
    - ./gradlew deploy -PcopyTo=../../../../extension/server

  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/extension/server/c4-language-server
    expire_in: 60 min

c4-language-client:
  image: node:16
  stage: client
  variables:
    NODE_ENV: "development"
  script:
    - cd extension
    - yarn install
    - yarn build
    - yarn global add vsce
    - find . -name *.jar
    - vsce package
  dependencies:
    - c4-language-server
  artifacts:
    paths:
      - $CI_PROJECT_DIR/extension/*.vsix
    expire_in: 1 day

pages:
  stage: deploy
  dependencies:
    - c4-language-server
  script:
    - mv $CI_PROJECT_DIR/$LANGUAGE_SERVER_DIR/build/reports/jacoco/test/html public
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
