stages:
  - server
  - client

c4-language-server:
  image: java:8-jdk
  stage: server

  script:
    - cd c4-language-server
    - ./gradlew check
    - ./gradlew deployToVSCode

  artifacts:
    paths: 
      - extension/server/c4-language-server
    expire_in: 60 min

c4-language-client:
  image: node:10
  stage: client

  variables:
    NODE_ENV: "development"

  script:
    - cd extension
    - yarn install 
    - yarn build
    - yarn global add vsce
    - vsce package

  dependencies:
    - c4-language-server

  artifacts:
    paths:
      - extension/*.vsix
    expire_in: 1 day