stages:
  - server
  - client

c4-language-server:
  image: java:8-jdk
  stage: server

  script:
    - cd c4-language-server
    - ./gradlew check
    - ./gradlew deployToVSCode

c4-language-client:
  image: node:10
  stage: client

  variables:
    NODE_ENV: "development"

  script:
    - cd extension
    - yarn install 
    - yarn build