image: "ubuntu:bionic"

before_script:
  - apt-get update
  - apt-get -y install openjdk-8-jdk
  - chmod +x c4-language-server/gradlew

stages:
  - test
  - build

language-server-test:
  stage: test

  script:
    - cd c4-language-server
    - ./gradlew check

language-server-build:
  stage: build

  script:
    - cd c4-language-server
    - ./gradlew deployToVSCode