image: "node:10"

before_script:
  - apt-get update
  - apt-get install -y openjdk-8-jdk 
  - apt-get install -y ant
  - apt-get clean
  - rm -rf /var/lib/apt/lists/*
  - rm -rf /var/cache/oracle-jdk8-installer
  - apt-get -y install openjdk-8-jdk
  - chmod +x c4-language-server/gradlew

stages:
  - server
  - client

c4-language-server:
  stage: server

  script:
    - cd c4-language-server
    - ./gradlew check
    - ./gradlew deployToVSCode

c4-language-client:
  stage: client

  variables:
    NODE_ENV: "development"

  script:
    - cd extension
    - yarn install 
    - yarn build