/*
 * generated by Xtext 2.20.0
 */
package de.systemticks.c4


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class C4DslStandaloneSetup extends C4DslStandaloneSetupGenerated {

	def static void doSetup() {
		new C4DslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
