/*
 * generated by Xtext 2.20.0
 */
package de.systemticks.c4.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
class C4DslProposalProvider extends AbstractC4DslProposalProvider {
}
