/*
 * generated by Xtext 2.20.0
 */
package de.systemticks.c4


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class C4DslRuntimeModule extends AbstractC4DslRuntimeModule {
}
