/*
 * generated by Xtext 2.20.0
 */
package de.systemticks.c4.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class C4DslUiModule extends AbstractC4DslUiModule {
}
